name: Build and Push Backend and Frontend Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/jya-empower/agnes-frontend:latest ./
          docker tag ghcr.io/jya-empower/agnes-frontend:latest ghcr.io/jya-empower/agnes-frontend:latest
          docker push ghcr.io/jya-empower/agnes-frontend:latest
